# version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: finances_backend
    restart: always
    expose:
      - "8000"
    networks:
      - expenses_network
    environment:
      ENV: docker
      DATABASE_URL: postgresql://user:password@db:5432/finances

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: finances_frontend
    restart: always
    expose:
      - "80"
    networks:
      - expenses_network
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: finances_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finances
    volumes:
      - finances_pgdata:/var/lib/postgresql/data
    networks:
      - expenses_network

volumes:
  finances_pgdata:

networks:
  expenses_network:
    name: expenses_network

