version: "3.9"

services:
  backend:
    build: ./backend
    container_name: finances_backend
    restart: always
    expose:
      - "8000"
    networks:
      - club-manager_default

  frontend:
    build: ./frontend
    container_name: finances_frontend
    restart: always
    expose:
      - "80"
    networks:
      - club-manager_default

  db:
    image: postgres:15-alpine
    container_name: finances_db
    restart: always
    environment:
      POSTGRES_USER: finances
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: finances
    volumes:
      - finances_pgdata:/var/lib/postgresql/data
    networks:
      - club-manager_default

volumes:
  finances_pgdata:

networks:
  club-manager_default:
    external: true
